<nav class="navbar navbar-fixed-top" style="border-radius: 0 0 50px 50px;">
    <div class="container">
        <div class="navbar-header">
            <button type="button" class="navbar-togglee pull-right" data-toggle="collapsee" data-target="#menu">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="/"><img src="/img/sliders/logos/utwhite.png" class="nav-log, animated bounceInRight delay-2s" alt="UT Chilapa" /></a>
        </div>
        <div class="collapsee navbar-collapsee" id="menu">
            <ul class="navbar-nav navbar-right, animated bounceInLeft delay-1s">
                <li><a href="/">Inicio</a></li>
                <li><a href="/nuestra-universidad/">Nuestra Universidad</a></li>
                <li class="dropdownn">
                    <a href="#" class="dropdown-togglee">Alumnos <b class="carett"></b></a>
                    <ul class="dropdown-menuu">
                    <li><a href="http://sia.uarm.utrng.edu.mx/">SIA</a></li>
                        <li><a href="/reglamentos/">Reglamentos</a></li>
                        <li><a href="/calendario/">Calendario Escolar</a></li>
                       
                        <li class="dropdownn">
                            <a href="#" class="dropdown-togglee">Becas <b class="carett right"></b></a>
                            <ul class="dropdown-menuu">
                                <li  class="dropdownn">
                                    <a href="/becasint/"> <!--class="dropdown-togglee" > --> Becas Internas </a>
                                </li>
                                <li class="divider"></li>
                                <li><a href="/becasext/">Becas Externas</a></li>
                            </ul>
                        </li>
                        <li class="divider"></li>
                        <li class="dropdownn">
                            <a href="#" class="dropdown-togglee">Biblioteca <b class="carett right"></b></a>
                            <ul class="dropdown-menuu">
                                <li  class="dropdownn">
                                    <a href="http://www.bibliotecaecest.mx/">Biblioteca Ecest</a>
                                </li>
                                <li class="divider"></li>
                                <li><a href="https://s3v2.solucionesdigitales.com.mx/BibliotecaDigital/">Biblioteca Digital</a></li>
                            </ul>
                        </li>
                    </ul>
                </li>
                <li class="dropdownn">
                    <a href="#" class="dropdown-togglee">Oferta Educativa <b class="carett"></b></a>
                    <ul class="dropdown-menuu">
                        <li class="dropdownn">
                            <a href="#" class="dropdown-togglee">TSU <b class="carett right"></b></a>
                            <ul class="dropdown-menuu">
                                <li class="dropdownn">
                                    <a href="#" class="dropdown-togglee">Tecnologías de la Información <b class="carett right"></b><br /> y Comunicación</a>
                                    <ul class="dropdown-menuu">
                                        <li><a href="/oferta-educativa/tsu-tic/">Escolarizado</a></li>
                                        <li><a href="/oferta-educativa/tsu-tic-despresurizado/">Despresurizado</a></li>
                                    </ul>
                                </li>
                                <li class="divider"></li>
                                <li><a href="/oferta-educativa/tsu-contaduria/">Contaduría</a></li>
                                <li><a href="/oferta-educativa/tsu-desarollodenegocios/">Desarrollo de negocios</a></li>
                            </ul>
                        </li>
                        <li class="divider"></li>
                        <li class="dropdownn">
                            <a href="#" class="dropdown-togglee">Ingenería <b class="carett right"></b></a>
                            <ul class="dropdown-menuu">
                                <li class="dropdownn">
                                    <a href="#" class="dropdown-togglee">Tecnologías de la Información <b class="carett right"></b></a>
                                    <ul class="dropdown-menuu">
                                        <li><a href="/oferta-educativa/ing-ti/">Escolarizado</a></li>
                                        <li><a href="/oferta-educativa/ing-ti-despresurizado/">Despresurizado</a></li>
                                    </ul>
                                </li>
                                <li class="divider"></li>
                                <li><a href="/oferta-educativa/ing-iff/">Financiera y Fiscal</a></li>
                                <li><a href="/oferta-educativa/ing-die/">Desarrollo e Innovación Empresarial</a></li>
                            </ul>
                        </li>
                        <li class="divider"></li>
                        <li class="dropdownn">
                            <a href="#" class="dropdown-togglee">Licenciatura <b class="carett right"></b></a>
                            <ul class="dropdown-menuu">
                                <li><a href="/oferta-educativa/lic-innovacion/">Licenciatura en Innovación de Negocios y Mercadotecnia</a></li>
                            </ul>
                        </li>
                    </ul>
                </li>
                <li class="dropdownn">
                    <a href="#" class="dropdown-togglee">Servicios Escolares <b class="carett"></b></a>
                    <ul class="dropdown-menuu">
                        <li><a href="/requisitos-para-titulacion/">Requisitos para tramite de Título</a></li>
                        <li><a href="/consultas-de-titulo/">Consultas de Título</a></li>
                    </ul>
                </li>
                <li class="dropdownn">
                    <a href="#" class="dropdown-togglee">Vinculación <b class="carett"></b></a>
                    <ul class="dropdown-menuu">
                        <li><a href="/oferta-educativa/estadia/">Estadías</a></li>
                        <li><a href="/visitas-industriales/">Visitas Industriales</a></li>
                        <li><a href="/promocion/">Promoción y Difusión</a></li>
                        <li><a href="/seguimiento-a-egresados/">Seguimiento a Egresados</a></li>
                        <li class="dropdownn">
                            <a href="#" class="dropdown-togglee">Movilidad<b class="carett right"></b></a>
                            <ul class="dropdown-menuu">
                                <li><a href="/movilidad-estudiantil/">Estudiantil</a></li>
                                <li><a href="/movilidad-docentes/">Docentes</a></li>
                            </ul>
                        </li>
                        <li><a href="http://www.saemx150.trabajando.com" target="_blank">Bolsa de Trabajo</a></li>
                    </ul>
                </li>
                <li><a href="/directorio/">Directorio</a></li>
                <li class="dropdownn">
                    
                </li>
            </ul>
               
        </div>
    </div>
</nav>